const mongoose = require('mongoose')

const MONGODB_URI = 'mongodb+srv://avidela47:avupk014@cluster0.9herq1s.mongodb.net/ferreteria-rios'

const fichasNuevas = [
  { codigo: '21033', nombre: 'Buje reduccion polipropileno 1 x 1/2', categoria: 'Plomeria', descripcion: 'Buje de reducción de polipropileno para cambiar de diámetro en una instalación.', paraQueSirve: 'Adaptar dos diámetros distintos de caño en una misma línea de agua.', quienLoPide: 'Plomero al conectar caños de distinto diámetro.', comoSeUsa: 'Roscar o termofusionar según el sistema, uniendo el diámetro mayor con el menor.', ventaCruzada: [], datosClave: 'Verificar ambos diámetros antes de comprar.', formaApariencia: 'Pieza corta con un extremo más ancho que el otro.', activo: true },
  { codigo: '21034', nombre: 'Buje reduccion polipropileno 1 x 3/4', categoria: 'Plomeria', descripcion: 'Buje de reducción de polipropileno para cambiar de diámetro en una instalación.', paraQueSirve: 'Adaptar dos diámetros distintos de caño en una misma línea de agua.', quienLoPide: 'Plomero al conectar caños de distinto diámetro.', comoSeUsa: 'Roscar o termofusionar según el sistema, uniendo el diámetro mayor con el menor.', ventaCruzada: [], datosClave: 'Verificar ambos diámetros antes de comprar.', formaApariencia: 'Pieza corta con un extremo más ancho que el otro.', activo: true },
  { codigo: '21031', nombre: 'Buje reduccion polipropileno 1/2 x 3/8', categoria: 'Plomeria', descripcion: 'Buje de reducción de polipropileno para cambiar de diámetro en una instalación.', paraQueSirve: 'Adaptar dos diámetros distintos de caño en una misma línea de agua.', quienLoPide: 'Plomero al conectar caños de distinto diámetro.', comoSeUsa: 'Roscar o termofusionar según el sistema, uniendo el diámetro mayor con el menor.', ventaCruzada: [], datosClave: 'Verificar ambos diámetros antes de comprar.', formaApariencia: 'Pieza corta con un extremo más ancho que el otro.', activo: true },
  { codigo: '21032', nombre: 'Buje reduccion polipropileno 3/4 x 1/2', categoria: 'Plomeria', descripcion: 'Buje de reducción de polipropileno para cambiar de diámetro en una instalación.', paraQueSirve: 'Adaptar dos diámetros distintos de caño en una misma línea de agua.', quienLoPide: 'Plomero al conectar caños de distinto diámetro.', comoSeUsa: 'Roscar o termofusionar según el sistema, uniendo el diámetro mayor con el menor.', ventaCruzada: [], datosClave: 'Verificar ambos diámetros antes de comprar.', formaApariencia: 'Pieza corta con un extremo más ancho que el otro.', activo: true },
  { codigo: '21360', nombre: 'Caño polipropileno tricapa 1/2 x 4 Mt.', categoria: 'Plomeria', descripcion: 'Caño de polipropileno tricapa para instalaciones de agua fría y caliente.', paraQueSirve: 'Conducir agua en instalaciones nuevas, resistente a altas temperaturas.', quienLoPide: 'Plomero en instalaciones de agua nuevas o reformas.', comoSeUsa: 'Cortar a medida y unir por termofusión con los accesorios correspondientes.', ventaCruzada: [], datosClave: 'Soporta agua caliente, a diferencia del PVC común.', formaApariencia: 'Caño rígido de tres capas, blanco o gris.', activo: true },
  { codigo: '21361', nombre: 'Caño polipropileno tricapa 3/4 x 4 Mt.', categoria: 'Plomeria', descripcion: 'Caño de polipropileno tricapa para instalaciones de agua fría y caliente.', paraQueSirve: 'Conducir agua en instalaciones nuevas, resistente a altas temperaturas.', quienLoPide: 'Plomero en instalaciones de agua nuevas o reformas.', comoSeUsa: 'Cortar a medida y unir por termofusión con los accesorios correspondientes.', ventaCruzada: [], datosClave: 'Soporta agua caliente, a diferencia del PVC común.', formaApariencia: 'Caño rígido de tres capas, blanco o gris.', activo: true },
  { codigo: '21115', nombre: 'Codo espiga por espiga 1/2', categoria: 'Plomeria', descripcion: 'Codo de polipropileno con espigas para termofusionar, cambia la dirección del caño.', paraQueSirve: 'Cambiar la dirección de una instalación de agua en polipropileno.', quienLoPide: 'Plomero en instalaciones con caños de polipropileno.', comoSeUsa: 'Termofusionar ambos extremos con el caño usando máquina soldadora de PP.', ventaCruzada: [], datosClave: 'Requiere máquina termofusora para instalar correctamente.', formaApariencia: 'Pieza curva de plástico rígido con dos bocas lisas.', activo: true },
  { codigo: '21116', nombre: 'Codo espiga por espiga 3/4', categoria: 'Plomeria', descripcion: 'Codo de polipropileno con espigas para termofusionar, cambia la dirección del caño.', paraQueSirve: 'Cambiar la dirección de una instalación de agua en polipropileno.', quienLoPide: 'Plomero en instalaciones con caños de polipropileno.', comoSeUsa: 'Termofusionar ambos extremos con el caño usando máquina soldadora de PP.', ventaCruzada: [], datosClave: 'Requiere máquina termofusora para instalar correctamente.', formaApariencia: 'Pieza curva de plástico rígido con dos bocas lisas.', activo: true },
  { codigo: '21001', nombre: 'Codo polipropileno 90º HH 1/2', categoria: 'Plomeria', descripcion: 'Codo de polipropileno roscado para cambiar la dirección de una instalación de agua.', paraQueSirve: 'Cambiar la dirección de caños de polipropileno en 90 grados.', quienLoPide: 'Plomero en instalaciones de agua con polipropileno.', comoSeUsa: 'Roscar en ambos extremos o termofusionar según el modelo (H hembra, M macho).', ventaCruzada: [], datosClave: 'Verificar si es rosca hembra (H) o macho (M) antes de comprar.', formaApariencia: 'Pieza curva de plástico con rosca en uno o los dos extremos.', activo: true },
  { codigo: '21002', nombre: 'Codo polipropileno 90º HH 3/4', categoria: 'Plomeria', descripcion: 'Codo de polipropileno roscado para cambiar la dirección de una instalación de agua.', paraQueSirve: 'Cambiar la dirección de caños de polipropileno en 90 grados.', quienLoPide: 'Plomero en instalaciones de agua con polipropileno.', comoSeUsa: 'Roscar en ambos extremos o termofusionar según el modelo (H hembra, M macho).', ventaCruzada: [], datosClave: 'Verificar si es rosca hembra (H) o macho (M) antes de comprar.', formaApariencia: 'Pieza curva de plástico con rosca en uno o los dos extremos.', activo: true },
  { codigo: '21006', nombre: 'Codo polipropileno 90º MH 1/2', categoria: 'Plomeria', descripcion: 'Codo de polipropileno roscado para cambiar la dirección de una instalación de agua.', paraQueSirve: 'Cambiar la dirección de caños de polipropileno en 90 grados.', quienLoPide: 'Plomero en instalaciones de agua con polipropileno.', comoSeUsa: 'Roscar en ambos extremos o termofusionar según el modelo (H hembra, M macho).', ventaCruzada: [], datosClave: 'Verificar si es rosca hembra (H) o macho (M) antes de comprar.', formaApariencia: 'Pieza curva de plástico con rosca en uno o los dos extremos.', activo: true },
  { codigo: '21007', nombre: 'Codo polipropileno 90º MH 3/4', categoria: 'Plomeria', descripcion: 'Codo de polipropileno roscado para cambiar la dirección de una instalación de agua.', paraQueSirve: 'Cambiar la dirección de caños de polipropileno en 90 grados.', quienLoPide: 'Plomero en instalaciones de agua con polipropileno.', comoSeUsa: 'Roscar en ambos extremos o termofusionar según el modelo (H hembra, M macho).', ventaCruzada: [], datosClave: 'Verificar si es rosca hembra (H) o macho (M) antes de comprar.', formaApariencia: 'Pieza curva de plástico con rosca en uno o los dos extremos.', activo: true },
  { codigo: '21110', nombre: 'Codo rosca 1/2 H por espiga 1/2', categoria: 'Plomeria', descripcion: 'Codo de polipropileno con espigas para termofusionar, cambia la dirección del caño.', paraQueSirve: 'Cambiar la dirección de una instalación de agua en polipropileno.', quienLoPide: 'Plomero en instalaciones con caños de polipropileno.', comoSeUsa: 'Termofusionar ambos extremos con el caño usando máquina soldadora de PP.', ventaCruzada: [], datosClave: 'Requiere máquina termofusora para instalar correctamente.', formaApariencia: 'Pieza curva de plástico rígido con dos bocas lisas.', activo: true },
  { codigo: '21050', nombre: 'Conexion tanque polipropileno 1/2', categoria: 'Plomeria', descripcion: 'Conexión de polipropileno para la salida de agua del tanque.', paraQueSirve: 'Conectar la salida del tanque de agua a la instalación de la casa.', quienLoPide: 'Plomero al instalar o reparar la salida del tanque.', comoSeUsa: 'Roscar o termofusionar en la base del tanque según el modelo.', ventaCruzada: [], datosClave: 'Verificar el diámetro de salida del tanque antes de comprar.', formaApariencia: 'Pieza corta con rosca en un extremo.', activo: true },
  { codigo: '21051', nombre: 'Conexion tanque polipropileno 3/4', categoria: 'Plomeria', descripcion: 'Conexión de polipropileno para la salida de agua del tanque.', paraQueSirve: 'Conectar la salida del tanque de agua a la instalación de la casa.', quienLoPide: 'Plomero al instalar o reparar la salida del tanque.', comoSeUsa: 'Roscar o termofusionar en la base del tanque según el modelo.', ventaCruzada: [], datosClave: 'Verificar el diámetro de salida del tanque antes de comprar.', formaApariencia: 'Pieza corta con rosca en un extremo.', activo: true },
  { codigo: '21016', nombre: 'Cupla polipropileno HH 1/2', categoria: 'Plomeria', descripcion: 'Cupla de polipropileno para unir dos tramos de caño en línea recta.', paraQueSirve: 'Empalmar dos caños de polipropileno del mismo diámetro.', quienLoPide: 'Plomero al extender o reparar una instalación.', comoSeUsa: 'Termofusionar o roscar ambos extremos con los caños a unir.', ventaCruzada: [], datosClave: 'Verificar si es H (rosca hembra) o M (rosca macho) antes de comprar.', formaApariencia: 'Pieza corta cilíndrica con dos bocas.', activo: true },
  { codigo: '21017', nombre: 'Cupla polipropileno HH 3/4', categoria: 'Plomeria', descripcion: 'Cupla de polipropileno para unir dos tramos de caño en línea recta.', paraQueSirve: 'Empalmar dos caños de polipropileno del mismo diámetro.', quienLoPide: 'Plomero al extender o reparar una instalación.', comoSeUsa: 'Termofusionar o roscar ambos extremos con los caños a unir.', ventaCruzada: [], datosClave: 'Verificar si es H (rosca hembra) o M (rosca macho) antes de comprar.', formaApariencia: 'Pieza corta cilíndrica con dos bocas.', activo: true },
  { codigo: '21085', nombre: 'Cupla polipropileno MH 1/2', categoria: 'Plomeria', descripcion: 'Cupla de polipropileno para unir dos tramos de caño en línea recta.', paraQueSirve: 'Empalmar dos caños de polipropileno del mismo diámetro.', quienLoPide: 'Plomero al extender o reparar una instalación.', comoSeUsa: 'Termofusionar o roscar ambos extremos con los caños a unir.', ventaCruzada: [], datosClave: 'Verificar si es H (rosca hembra) o M (rosca macho) antes de comprar.', formaApariencia: 'Pieza corta cilíndrica con dos bocas.', activo: true },
  { codigo: '21086', nombre: 'Cupla polipropileno MH 3/4', categoria: 'Plomeria', descripcion: 'Cupla de polipropileno para unir dos tramos de caño en línea recta.', paraQueSirve: 'Empalmar dos caños de polipropileno del mismo diámetro.', quienLoPide: 'Plomero al extender o reparar una instalación.', comoSeUsa: 'Termofusionar o roscar ambos extremos con los caños a unir.', ventaCruzada: [], datosClave: 'Verificar si es H (rosca hembra) o M (rosca macho) antes de comprar.', formaApariencia: 'Pieza corta cilíndrica con dos bocas.', activo: true },
  { codigo: '21087', nombre: 'Cupla reduccion polipropileno HH 3/4 x 1/2', categoria: 'Plomeria', descripcion: 'Cupla de polipropileno para unir dos tramos de caño en línea recta.', paraQueSirve: 'Empalmar dos caños de polipropileno del mismo diámetro.', quienLoPide: 'Plomero al extender o reparar una instalación.', comoSeUsa: 'Termofusionar o roscar ambos extremos con los caños a unir.', ventaCruzada: [], datosClave: 'Verificar si es H (rosca hembra) o M (rosca macho) antes de comprar.', formaApariencia: 'Pieza corta cilíndrica con dos bocas.', activo: true },
  { codigo: '21105', nombre: 'Espiga 1/2 Rosca hembra 1/2', categoria: 'Plomeria', descripcion: 'Espiga de polipropileno con rosca de un lado para conectar con canillas o artefactos.', paraQueSirve: 'Conectar una instalación de polipropileno termofusionado con un artefacto roscado.', quienLoPide: 'Plomero al instalar una canilla o artefacto sobre polipropileno.', comoSeUsa: 'Roscar un extremo con teflón y termofusionar el otro con el caño.', ventaCruzada: [], datosClave: 'Verificar si es rosca hembra o macho antes de comprar.', formaApariencia: 'Pieza corta con un extremo roscado y otro liso.', activo: true },
  { codigo: '21100', nombre: 'Espiga 1/2 Rosca macho 1/2', categoria: 'Plomeria', descripcion: 'Espiga de polipropileno con rosca de un lado para conectar con canillas o artefactos.', paraQueSirve: 'Conectar una instalación de polipropileno termofusionado con un artefacto roscado.', quienLoPide: 'Plomero al instalar una canilla o artefacto sobre polipropileno.', comoSeUsa: 'Roscar un extremo con teflón y termofusionar el otro con el caño.', ventaCruzada: [], datosClave: 'Verificar si es rosca hembra o macho antes de comprar.', formaApariencia: 'Pieza corta con un extremo roscado y otro liso.', activo: true },
  { codigo: '21106', nombre: 'Espiga 3/4 Rosca hembra 3/4', categoria: 'Plomeria', descripcion: 'Espiga de polipropileno con rosca de un lado para conectar con canillas o artefactos.', paraQueSirve: 'Conectar una instalación de polipropileno termofusionado con un artefacto roscado.', quienLoPide: 'Plomero al instalar una canilla o artefacto sobre polipropileno.', comoSeUsa: 'Roscar un extremo con teflón y termofusionar el otro con el caño.', ventaCruzada: [], datosClave: 'Verificar si es rosca hembra o macho antes de comprar.', formaApariencia: 'Pieza corta con un extremo roscado y otro liso.', activo: true },
  { codigo: '21101', nombre: 'Espiga 3/4 Rosca macho 3/4', categoria: 'Plomeria', descripcion: 'Espiga de polipropileno con rosca de un lado para conectar con canillas o artefactos.', paraQueSirve: 'Conectar una instalación de polipropileno termofusionado con un artefacto roscado.', quienLoPide: 'Plomero al instalar una canilla o artefacto sobre polipropileno.', comoSeUsa: 'Roscar un extremo con teflón y termofusionar el otro con el caño.', ventaCruzada: [], datosClave: 'Verificar si es rosca hembra o macho antes de comprar.', formaApariencia: 'Pieza corta con un extremo roscado y otro liso.', activo: true },
  { codigo: '21125', nombre: 'Espiga TEE Triple espiga 1/2', categoria: 'Plomeria', descripcion: 'TEE de polipropileno con espigas para termofusionar, deriva la instalación en tres direcciones.', paraQueSirve: 'Derivar una línea de agua en tres direcciones (ramificar la instalación).', quienLoPide: 'Plomero al ramificar una instalación de polipropileno.', comoSeUsa: 'Termofusionar las tres bocas con los caños correspondientes.', ventaCruzada: [], datosClave: 'Requiere máquina termofusora.', formaApariencia: 'Pieza en forma de T con tres bocas.', activo: true },
  { codigo: '21126', nombre: 'Espiga TEE Triple espiga 3/4', categoria: 'Plomeria', descripcion: 'TEE de polipropileno con espigas para termofusionar, deriva la instalación en tres direcciones.', paraQueSirve: 'Derivar una línea de agua en tres direcciones (ramificar la instalación).', quienLoPide: 'Plomero al ramificar una instalación de polipropileno.', comoSeUsa: 'Termofusionar las tres bocas con los caños correspondientes.', ventaCruzada: [], datosClave: 'Requiere máquina termofusora.', formaApariencia: 'Pieza en forma de T con tres bocas.', activo: true },
  { codigo: '21130', nombre: 'Espiga TEE rosca H 1/2 espiga 1/2 espiga 1/2', categoria: 'Plomeria', descripcion: 'TEE de polipropileno con espigas para termofusionar, deriva la instalación en tres direcciones.', paraQueSirve: 'Derivar una línea de agua en tres direcciones (ramificar la instalación).', quienLoPide: 'Plomero al ramificar una instalación de polipropileno.', comoSeUsa: 'Termofusionar las tres bocas con los caños correspondientes.', ventaCruzada: [], datosClave: 'Requiere máquina termofusora.', formaApariencia: 'Pieza en forma de T con tres bocas.', activo: true },
  { codigo: '21131', nombre: 'Espiga TEE rosca H 3/4 espiga 3/4 espiga 3/4', categoria: 'Plomeria', descripcion: 'TEE de polipropileno con espigas para termofusionar, deriva la instalación en tres direcciones.', paraQueSirve: 'Derivar una línea de agua en tres direcciones (ramificar la instalación).', quienLoPide: 'Plomero al ramificar una instalación de polipropileno.', comoSeUsa: 'Termofusionar las tres bocas con los caños correspondientes.', ventaCruzada: [], datosClave: 'Requiere máquina termofusora.', formaApariencia: 'Pieza en forma de T con tres bocas.', activo: true },
  { codigo: '21120', nombre: 'Espiga doble 1/2 espiga por espiga', categoria: 'Plomeria', descripcion: 'Espiga doble de polipropileno para unir dos tramos de caño por termofusión.', paraQueSirve: 'Empalmar dos caños de polipropileno en línea recta por termofusión.', quienLoPide: 'Plomero en instalaciones con caños de polipropileno.', comoSeUsa: 'Termofusionar ambos extremos con los caños a unir.', ventaCruzada: [], datosClave: 'Requiere máquina termofusora.', formaApariencia: 'Pieza corta cilíndrica lisa en ambos extremos.', activo: true },
  { codigo: '21121', nombre: 'Espiga doble 3/4 espiga por espiga', categoria: 'Plomeria', descripcion: 'Espiga doble de polipropileno para unir dos tramos de caño por termofusión.', paraQueSirve: 'Empalmar dos caños de polipropileno en línea recta por termofusión.', quienLoPide: 'Plomero en instalaciones con caños de polipropileno.', comoSeUsa: 'Termofusionar ambos extremos con los caños a unir.', ventaCruzada: [], datosClave: 'Requiere máquina termofusora.', formaApariencia: 'Pieza corta cilíndrica lisa en ambos extremos.', activo: true },
  { codigo: '21140', nombre: 'Espiga reduccion espiga 3/4 x espiga 1/2', categoria: 'Plomeria', descripcion: 'Espiga de reducción de polipropileno para cambiar de diámetro por termofusión.', paraQueSirve: 'Adaptar dos diámetros distintos de caño de polipropileno.', quienLoPide: 'Plomero al conectar caños de distinto diámetro.', comoSeUsa: 'Termofusionar ambos extremos, uniendo el diámetro mayor con el menor.', ventaCruzada: [], datosClave: 'Verificar ambos diámetros antes de comprar.', formaApariencia: 'Pieza corta con un extremo más ancho que el otro.', activo: true },
  { codigo: '21057', nombre: 'Niple polipropileno 1/2 x 10cm', categoria: 'Plomeria', descripcion: 'Niple de polipropileno, tramo corto para unir accesorios cercanos.', paraQueSirve: 'Conectar dos accesorios de polipropileno que están muy próximos entre sí.', quienLoPide: 'Plomero en instalaciones de polipropileno.', comoSeUsa: 'Termofusionar ambos extremos con los accesorios correspondientes.', ventaCruzada: [], datosClave: 'El largo determina la distancia entre los accesorios a conectar.', formaApariencia: 'Tramo corto de caño rígido.', activo: true },
  { codigo: '21058', nombre: 'Niple polipropileno 1/2 x 12cm', categoria: 'Plomeria', descripcion: 'Niple de polipropileno, tramo corto para unir accesorios cercanos.', paraQueSirve: 'Conectar dos accesorios de polipropileno que están muy próximos entre sí.', quienLoPide: 'Plomero en instalaciones de polipropileno.', comoSeUsa: 'Termofusionar ambos extremos con los accesorios correspondientes.', ventaCruzada: [], datosClave: 'El largo determina la distancia entre los accesorios a conectar.', formaApariencia: 'Tramo corto de caño rígido.', activo: true },
  { codigo: '21059', nombre: 'Niple polipropileno 1/2 x 15cm', categoria: 'Plomeria', descripcion: 'Niple de polipropileno, tramo corto para unir accesorios cercanos.', paraQueSirve: 'Conectar dos accesorios de polipropileno que están muy próximos entre sí.', quienLoPide: 'Plomero en instalaciones de polipropileno.', comoSeUsa: 'Termofusionar ambos extremos con los accesorios correspondientes.', ventaCruzada: [], datosClave: 'El largo determina la distancia entre los accesorios a conectar.', formaApariencia: 'Tramo corto de caño rígido.', activo: true },
  { codigo: '21056', nombre: 'Niple polipropileno 1/2 x 8cm', categoria: 'Plomeria', descripcion: 'Niple de polipropileno, tramo corto para unir accesorios cercanos.', paraQueSirve: 'Conectar dos accesorios de polipropileno que están muy próximos entre sí.', quienLoPide: 'Plomero en instalaciones de polipropileno.', comoSeUsa: 'Termofusionar ambos extremos con los accesorios correspondientes.', ventaCruzada: [], datosClave: 'El largo determina la distancia entre los accesorios a conectar.', formaApariencia: 'Tramo corto de caño rígido.', activo: true },
  { codigo: '21065', nombre: 'Niple polipropileno 3/4 x 12cm', categoria: 'Plomeria', descripcion: 'Niple de polipropileno, tramo corto para unir accesorios cercanos.', paraQueSirve: 'Conectar dos accesorios de polipropileno que están muy próximos entre sí.', quienLoPide: 'Plomero en instalaciones de polipropileno.', comoSeUsa: 'Termofusionar ambos extremos con los accesorios correspondientes.', ventaCruzada: [], datosClave: 'El largo determina la distancia entre los accesorios a conectar.', formaApariencia: 'Tramo corto de caño rígido.', activo: true },
  { codigo: '21066', nombre: 'Niple polipropileno 3/4 x 15cm', categoria: 'Plomeria', descripcion: 'Niple de polipropileno, tramo corto para unir accesorios cercanos.', paraQueSirve: 'Conectar dos accesorios de polipropileno que están muy próximos entre sí.', quienLoPide: 'Plomero en instalaciones de polipropileno.', comoSeUsa: 'Termofusionar ambos extremos con los accesorios correspondientes.', ventaCruzada: [], datosClave: 'El largo determina la distancia entre los accesorios a conectar.', formaApariencia: 'Tramo corto de caño rígido.', activo: true },
  { codigo: '21062', nombre: 'Niple polipropileno 3/4 x 6cm', categoria: 'Plomeria', descripcion: 'Niple de polipropileno, tramo corto para unir accesorios cercanos.', paraQueSirve: 'Conectar dos accesorios de polipropileno que están muy próximos entre sí.', quienLoPide: 'Plomero en instalaciones de polipropileno.', comoSeUsa: 'Termofusionar ambos extremos con los accesorios correspondientes.', ventaCruzada: [], datosClave: 'El largo determina la distancia entre los accesorios a conectar.', formaApariencia: 'Tramo corto de caño rígido.', activo: true },
  { codigo: '21063', nombre: 'Niple polipropileno 3/4 x 8cm', categoria: 'Plomeria', descripcion: 'Niple de polipropileno, tramo corto para unir accesorios cercanos.', paraQueSirve: 'Conectar dos accesorios de polipropileno que están muy próximos entre sí.', quienLoPide: 'Plomero en instalaciones de polipropileno.', comoSeUsa: 'Termofusionar ambos extremos con los accesorios correspondientes.', ventaCruzada: [], datosClave: 'El largo determina la distancia entre los accesorios a conectar.', formaApariencia: 'Tramo corto de caño rígido.', activo: true },
  { codigo: '21037', nombre: 'Reduccion MM polipropileno 1 x 1/2', categoria: 'Plomeria', descripcion: 'Reducción macho-macho de polipropileno para unir dos diámetros distintos.', paraQueSirve: 'Adaptar dos diámetros distintos de caño de polipropileno con rosca macho en ambos extremos.', quienLoPide: 'Plomero al conectar caños de distinto diámetro.', comoSeUsa: 'Roscar ambos extremos con teflón sobre los accesorios correspondientes.', ventaCruzada: [], datosClave: 'Verificar ambos diámetros antes de comprar.', formaApariencia: 'Pieza corta con rosca macho en los dos extremos.', activo: true },
  { codigo: '21038', nombre: 'Reduccion MM polipropileno 1 x 3/4', categoria: 'Plomeria', descripcion: 'Reducción macho-macho de polipropileno para unir dos diámetros distintos.', paraQueSirve: 'Adaptar dos diámetros distintos de caño de polipropileno con rosca macho en ambos extremos.', quienLoPide: 'Plomero al conectar caños de distinto diámetro.', comoSeUsa: 'Roscar ambos extremos con teflón sobre los accesorios correspondientes.', ventaCruzada: [], datosClave: 'Verificar ambos diámetros antes de comprar.', formaApariencia: 'Pieza corta con rosca macho en los dos extremos.', activo: true },
  { codigo: '21036', nombre: 'Reduccion MM polipropileno 3/4 x 1/2', categoria: 'Plomeria', descripcion: 'Reducción macho-macho de polipropileno para unir dos diámetros distintos.', paraQueSirve: 'Adaptar dos diámetros distintos de caño de polipropileno con rosca macho en ambos extremos.', quienLoPide: 'Plomero al conectar caños de distinto diámetro.', comoSeUsa: 'Roscar ambos extremos con teflón sobre los accesorios correspondientes.', ventaCruzada: [], datosClave: 'Verificar ambos diámetros antes de comprar.', formaApariencia: 'Pieza corta con rosca macho en los dos extremos.', activo: true },
  { codigo: '21028', nombre: 'Rosca con tuerca polipropileno 3/4', categoria: 'Plomeria', descripcion: 'Unión roscada con tuerca de polipropileno, permite desmontar la instalación.', paraQueSirve: 'Conectar dos tramos de polipropileno de forma desmontable.', quienLoPide: 'Plomero que necesita poder desarmar la instalación en el futuro.', comoSeUsa: 'Termofusionar un extremo y roscar el otro con la tuerca de ajuste.', ventaCruzada: [], datosClave: 'Permite desmontar sin cortar el caño, a diferencia de una unión fija.', formaApariencia: 'Pieza con tuerca de ajuste visible.', activo: true },
  { codigo: '21011', nombre: 'TEE polipropileno HHH 1/2', categoria: 'Plomeria', descripcion: 'TEE de polipropileno roscada, deriva la instalación en tres direcciones.', paraQueSirve: 'Derivar una línea de agua en tres direcciones (ramificar la instalación).', quienLoPide: 'Plomero al ramificar una instalación de polipropileno.', comoSeUsa: 'Roscar las tres bocas con teflón sobre los caños correspondientes.', ventaCruzada: [], datosClave: 'Verificar el diámetro de las tres bocas antes de comprar.', formaApariencia: 'Pieza en forma de T con tres bocas roscadas.', activo: true },
  { codigo: '21012', nombre: 'TEE polipropileno HHH 3/4', categoria: 'Plomeria', descripcion: 'TEE de polipropileno roscada, deriva la instalación en tres direcciones.', paraQueSirve: 'Derivar una línea de agua en tres direcciones (ramificar la instalación).', quienLoPide: 'Plomero al ramificar una instalación de polipropileno.', comoSeUsa: 'Roscar las tres bocas con teflón sobre los caños correspondientes.', ventaCruzada: [], datosClave: 'Verificar el diámetro de las tres bocas antes de comprar.', formaApariencia: 'Pieza en forma de T con tres bocas roscadas.', activo: true },
  { codigo: '21041', nombre: 'Tapa H polipropileno 1/2', categoria: 'Plomeria', descripcion: 'Tapa de polipropileno para cerrar el extremo de un caño.', paraQueSirve: 'Cerrar el extremo de una línea de agua de polipropileno que no se va a usar.', quienLoPide: 'Plomero al finalizar o dejar preparada una instalación.', comoSeUsa: 'Roscar o termofusionar en el extremo del caño a tapar.', ventaCruzada: [], datosClave: 'Verificar si es rosca hembra (H) o macho (M) antes de comprar.', formaApariencia: 'Pieza corta ciega en un extremo.', activo: true },
  { codigo: '21042', nombre: 'Tapa H polipropileno 3/4', categoria: 'Plomeria', descripcion: 'Tapa de polipropileno para cerrar el extremo de un caño.', paraQueSirve: 'Cerrar el extremo de una línea de agua de polipropileno que no se va a usar.', quienLoPide: 'Plomero al finalizar o dejar preparada una instalación.', comoSeUsa: 'Roscar o termofusionar en el extremo del caño a tapar.', ventaCruzada: [], datosClave: 'Verificar si es rosca hembra (H) o macho (M) antes de comprar.', formaApariencia: 'Pieza corta ciega en un extremo.', activo: true },
  { codigo: '21046', nombre: 'Tapa M polipropileno 1/2', categoria: 'Plomeria', descripcion: 'Tapa de polipropileno para cerrar el extremo de un caño.', paraQueSirve: 'Cerrar el extremo de una línea de agua de polipropileno que no se va a usar.', quienLoPide: 'Plomero al finalizar o dejar preparada una instalación.', comoSeUsa: 'Roscar o termofusionar en el extremo del caño a tapar.', ventaCruzada: [], datosClave: 'Verificar si es rosca hembra (H) o macho (M) antes de comprar.', formaApariencia: 'Pieza corta ciega en un extremo.', activo: true },
  { codigo: 'TUBOT8C', nombre: 'Tubo LED T8 - Flujo lumínico: 1800 Lúmenes Calido', categoria: 'Electricidad', descripcion: 'Tubo LED T8 de luz cálida para reemplazar tubos fluorescentes.', paraQueSirve: 'Iluminar con tecnología LED de bajo consumo en artefactos existentes.', quienLoPide: 'Cliente que renueva la iluminación de su local o casa.', comoSeUsa: 'Instalar en el artefacto correspondiente, verificando compatibilidad eléctrica.', ventaCruzada: [], datosClave: 'Luz cálida (amarilla), verificar el largo antes de comprar.', formaApariencia: 'Tubo cilíndrico con conexión en los extremos.', activo: true },
  { codigo: '21021', nombre: 'Union doble conica polipropileno HH 1/2', categoria: 'Plomeria', descripcion: 'Unión doble cónica de polipropileno, permite desmontar la instalación sin cortar.', paraQueSirve: 'Conectar dos tramos de polipropileno de forma desmontable para mantenimiento.', quienLoPide: 'Plomero que necesita poder desarmar la instalación en el futuro.', comoSeUsa: 'Termofusionar ambos extremos y ajustar la tuerca central.', ventaCruzada: [], datosClave: 'Permite desarmar la unión sin cortar el caño.', formaApariencia: 'Pieza con tuerca central de ajuste.', activo: true },
  { codigo: '21022', nombre: 'Union doble conica polipropileno HH 3/4', categoria: 'Plomeria', descripcion: 'Unión doble cónica de polipropileno, permite desmontar la instalación sin cortar.', paraQueSirve: 'Conectar dos tramos de polipropileno de forma desmontable para mantenimiento.', quienLoPide: 'Plomero que necesita poder desarmar la instalación en el futuro.', comoSeUsa: 'Termofusionar ambos extremos y ajustar la tuerca central.', ventaCruzada: [], datosClave: 'Permite desarmar la unión sin cortar el caño.', formaApariencia: 'Pieza con tuerca central de ajuste.', activo: true },
]

async function main() {
  await mongoose.connect(MONGODB_URI)
  console.log('Conectado a MongoDB')

  const db = mongoose.connection
  const ultima = await db.collection('fichas').find().sort({ id_ficha: -1 }).limit(1).toArray()

  const resultado = await db.collection('fichas').insertMany(fichasNuevas)
  console.log('Fichas insertadas: ' + resultado.insertedCount)

  await mongoose.disconnect()
  console.log('Listo')
}

main().catch(console.error)